name: Handshake Docs
url: https://
description: Docs for the Handshake project
exclude:
  - README.md
  - Gemfile*
plugins:
  - jekyll-sitemap
sass:
  sass_dir: css
sitemap:
  file: "/sitemap.xml"
compress_html:
  # clippings: all
  # comments: ["<!-- ", " -->"]
  blanklines: true

collections:
  faqs:
    output: true
    permalink: /faq/:name
  docs:
    output: true
    permalink: /doc/:name
    layout: default

defaults: 
  - scope:
     path: ""
     type: "faqs"
    values:
      layout: default


# Build settings
markdown: kramdown
permalinks: pretty
