name: Handshake Blog
url: https://blog.handshake.org/
description: Handshake Blog
exclude:
  - README.md
  - Gemfile*
plugins:
  - jekyll-sitemap
sass:
  sass_dir: css
sitemap:
  file: "/sitemap.xml"
compress_html:
  # clippings: all
  # comments: ["<!-- ", " -->"]
  blanklines: true

collections:
  articles:
    output: true
    permalink: /:name
    layout: article

defaults: 
  - scope:
     path: ""
     type: "articles"
    values:
      layout: default


# Build settings
markdown: kramdown
permalinks: pretty
